#!/bin/sh

mycache=~/executables.cache

choice=`cat $mycache | \
  dmenu -i -l 32 \
  -fn 12x24 \
  -nf yellow -nb black -sf black -sb white`

[ "$?" = "0" ] && exec $choice

list_executables_on_path.sh > $mycache
